### Label Encoding
Label encoding is a fundamental data preprocessing technique used to convert categorical data into a numerical format suitable for machine learning models. Many algorithms cannot process non-numeric values, making encoding a necessary step when working with features such as colors, cities or product types.

In [24]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [25]:
## Create a simple data frame
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [26]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [34]:
lbl_encoder = LabelEncoder()

In [35]:
lbl_encoder.fit_transform(df[['color']])

c:\DS and ML\venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [ ]:
lbl_encoder.transform([['blue']])

c:\DS and ML\venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [39]:
lbl_encoder.transform([['red']])

c:\DS and ML\venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

### Ordinal Encoding

Ordinal encoding is a technique used to convert categorical data into numerical values while preserving the inherent order or hierarchy among the categories. This is particularly useful in machine learning, as many algorithms perform better with numerical data. For example, in a dataset with shirt sizes like "Small," "Medium," and "Large," ordinal encoding can assign values such as 1, 2, and 3, respectively, to reflect their natural ranking.

In [40]:
import pandas as pd

In [41]:
from sklearn.preprocessing import OrdinalEncoder

In [43]:
df1=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [44]:
df1

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [50]:
encoder = OrdinalEncoder(categories=[['small','medium','large']])

In [52]:
encoder.fit_transform(df1[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [62]:
encoder.transform([['small']])

c:\DS and ML\venv\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])