In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('economic_index.csv')
df.head()

   Unnamed: 0  year  month  interest_rate  unemployment_rate  index_price
0           0  2017     12           2.75                5.3         1464
1           1  2017     11           2.50                5.3         1394
2           2  2017     10           2.50                5.3         1357
3           3  2017      9           2.50                5.3         1293
4           4  2017      8           2.50                5.4         1256

In [3]:
df.columns

Index(['Unnamed: 0', 'year', 'month', 'interest_rate', 'unemployment_rate',
       'index_price'],
      dtype='object')

In [4]:
df.drop(columns=['Unnamed: 0','year','month'],axis=1,inplace=True)
df.head()

   interest_rate  unemployment_rate  index_price
0           2.75                5.3         1464
1           2.50                5.3         1394
2           2.50                5.3         1357
3           2.50                5.3         1293
4           2.50                5.4         1256

In [5]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [7]:
from sklearn.linear_model import Ridge

In [8]:
reg=Ridge(alpha=10)

In [9]:
reg.fit(X_train,y_train)

Ridge(alpha=10)

In [10]:
print(reg.coef_)
print(reg.intercept_)

[ 86.05457551 -83.30180188]
1357.8537834029873

### SCRATCH

In [11]:
class RRegressor:
    def __init__(self, alpha):
        self.alpha = alpha
        self.intercept_=None
        self.coef_=None

    def fit(self, X_train, y_train):
        X = np.hstack((np.ones((X_train.shape[0], 1)), X_train))
        print(X)

        I = np.eye(X.shape[1])
        I[0, 0] = 0   

        m = np.linalg.inv(X.T @ X + self.alpha * I) @ X.T @ y_train

        self.intercept_ = m[0]
        self.coef_ = m[1:]

In [12]:
ridge1=RRegressor(10)
ridge1.fit(X_train,y_train)
print(ridge1.coef_)
print(ridge1.intercept_)

[[1.   1.75 5.9 ]
 [1.   2.5  5.3 ]
 [1.   1.75 6.2 ]
 [1.   2.5  5.6 ]
 [1.   2.5  5.3 ]
 [1.   2.   6.  ]
 [1.   1.75 6.1 ]
 [1.   2.5  5.3 ]
 [1.   2.5  5.4 ]
 [1.   1.75 6.2 ]
 [1.   1.75 6.1 ]
 [1.   1.75 5.9 ]
 [1.   1.75 6.1 ]
 [1.   2.25 5.5 ]
 [1.   2.   5.7 ]
 [1.   1.75 5.8 ]
 [1.   1.75 6.1 ]
 [1.   2.5  5.5 ]]
[ 86.05457551 -83.30180188]
1357.8537834029783

### Gradient Descent

In [ ]:
import numpy as np

class GDregressor:
    def __init__(self, eta=0.01, epoch=1000):
        self.eta = eta
        self.epoch = epoch
        self.w = None
        self.b = None

    def fit(self, X_train, y_train):
        m, n = X_train.shape

        X = np.hstack((np.ones((m, 1)), X_train))

        self.w = np.zeros(n + 1)

        for i in range(self.epoch):
            y_pred = X @ self.w
            error = y_pred - y_train

            dw = (2/m) * (X.T @ error)

            self.w -= self.eta * dw

        self.b = self.w[0]
        self.w = self.w[1:]

In [15]:
ridge2=GDregressor()
ridge2.fit(X_train,y_train)
print(ridge2.w)
print(ridge2.b)

[546.5634444  -25.49525911]
76.3700676640358