In [204]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler

In [205]:
df=sns.load_dataset('tips')

In [206]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [207]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [208]:
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [209]:
X=df.drop('total_bill',axis=1)
y=df['total_bill']

In [210]:
le = LabelEncoder()
cols = ['sex','smoker','time']

for col in cols:
    X[col] = le.fit_transform(X[col])

In [211]:
X.head()

    tip  sex  smoker  day  time  size
0  1.01    0       0  Sun     0     2
1  1.66    1       0  Sun     0     3
2  3.50    1       0  Sun     0     3
3  3.31    1       0  Sun     0     2
4  3.61    0       0  Sun     0     4

In [212]:
ohe=OneHotEncoder()
encoded = ohe.fit_transform(X[['day']]).toarray()

In [213]:
encoded_df = pd.DataFrame(encoded,columns=ohe.get_feature_names_out())

In [214]:
df=pd.concat((df,encoded_df),axis=1)

In [217]:
df=df.drop('day',axis=1)

In [218]:
df.head()

,total_bill,tip,sex,smoker,time,size,day_Fri,day_Sat,day_Sun,day_Thur
0,16.99,1.01,Female,No,Dinner,2,0.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Dinner,3,0.0,0.0,1.0,0.0
2,21.01,3.50,Male,No,Dinner,3,0.0,0.0,1.0,0.0
3,23.68,3.31,Male,No,Dinner,2,0.0,0.0,1.0,0.0
4,24.59,3.61,Female,No,Dinner,4,0.0,0.0,1.0,0.0